theme: jekyll-theme-cayman
title: GloryVK
description: Расширение позволяет кардинально изменить внешний вид и функционал страницы ВКонтакте по вашему вкусу.
layout: home
avatar: https://pp.userapi.com/c841326/v841326704/2dbf5/OzrKHIaBM1U.jpg
show_downloads: true
